"""Shared repository paths for CartWise application code and scripts."""

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_ROOT = PROJECT_ROOT / "data"
RAW_DATA_ROOT = DATA_ROOT / "raw"
AMAZON_REVIEWS_RAW_ROOT = RAW_DATA_ROOT / "amazon_reviews_2023"
AMAZON_ESCI_RAW_ROOT = RAW_DATA_ROOT / "amazon_esci"
PROCESSED_ROOT = DATA_ROOT / "processed"
DEV_PROCESSED_ROOT = PROCESSED_ROOT / "dev"
PROCESSED_ROOTS = {
    "dev": DEV_PROCESSED_ROOT,
    "full": PROCESSED_ROOT,
}

MODELS_ROOT = PROJECT_ROOT / "models"
REPORTS_ROOT = PROJECT_ROOT / "reports"
METRICS_ROOT = REPORTS_ROOT / "metrics"

ARTIFACTS_ROOT = PROJECT_ROOT / "artifacts"
ARTIFACT_INDEXES_ROOT = ARTIFACTS_ROOT / "indexes"
ARTIFACT_REPORTS_ROOT = ARTIFACTS_ROOT / "reports"
ARTIFACT_PREVIEWS_ROOT = ARTIFACTS_ROOT / "previews"
PRODUCT_DENSE_ARTIFACT_ROOT = ARTIFACT_INDEXES_ROOT / "product_dense"
PRODUCT_BM25_ARTIFACT_ROOT = ARTIFACT_INDEXES_ROOT / "product_bm25"
EVIDENCE_DENSE_ARTIFACT_ROOT = ARTIFACT_INDEXES_ROOT / "evidence_dense"
RETRIEVAL_AUDIT_ARTIFACT_ROOT = ARTIFACT_REPORTS_ROOT / "retrieval_audit"
